### ISSUE TITLE
mpoonuru issue

### ISSUE THREAD

**Issue by Prophet731** [AdKats/BFAdminCP#250]
Created thread here so not spamming other.

**Comment by Prophet731** [comment]
@mpoonuru

How is your webserver setup? Do you use cpanel or some time of other CP or just manually manage it though shell?

**Comment by mpoonuru** [comment]
Hi friend, yes I use cPanel and ftp, don't have shell access, can we have a team viewer my friend? Or some other communication channel?

**Comment by mpoonuru** [comment]
I am sorry my friend, I know how it would be when we back home after the squeeze, not in a hurry, relax bro, whenever you have time , just let me know

**Comment by Prophet731** [comment]
Well it's a simple fix for you actually. The BFACP isn't designed to run from a folder on the TLD so this `admin.abc.zzz/bfacp` wouldn't work. You would need to configured the subdomain in cpanel to point to the public directory that's provided by the BFACP. This isn't a redirect, you are changing the document root to the subdomain to that folder. After you do that try loading the application again, make sure you upload a fresh copy and make sure no `bfacp_` tables in the database exist.. Also make sure that you have the vendor folder. Don't download from github, download from sourceforge (if you haven't yet) as that has all the required files with it. 

Then just follow the read me from the master branch and it'll explain the rest. However, if you wanna run the latest dev version (which includes some fixes since I last updated the master branch) you will need shell access to your webserver. If you've able to then just follow [these](https://github.com/Prophet731/BFAdminCP/tree/dev-laravel5#installing-dev-version) instructions instead.

**Comment by mpoonuru** [comment]
Hi Friend, you can see my latest URL, I did follow your doc, https:// admin. Corehqservers.com/public then I got the error in handling exception. You can access my URL, you will come to know,

**Comment by killengage** [comment]
Like @Prophet731 said BFACP doesn't work on a (sub)domain directory. So if you go to admin. Corehqservers.com/public  it doesn't work because you are trying to call the BFACP directory (public). 
Try to make a subdomain like bafcp.Corehqservers.com. After that install BFACP on this domain (in the www root). When you did this point the subdomain to the public folder (via Cpanel).

**Comment by mpoonuru** [comment]
Sure My Friends, Let me try this, If I run into issues, I will let you know. Thank you.

**Comment by mpoonuru** [comment]
I got the same error my friends.

Error in exception handler.

now my document root points to public and still I get this error!

**Comment by killengage** [comment]
What subdomain did you create ?

**Comment by killengage** [comment]
It is working for me. https://ibb.co/hQixFa

**Comment by mpoonuru** [comment]
same subdomain. but changed the document root. Deleted all the existing files, downloaded a copy from Sourceforge and uploaded to my subdomain. Extracted all the files. 
dropped the tables, updated .env.php file and changed the app/storage permissions.

Then ran it and I did get the same issue. Will you be able to use team viewer?

**Comment by killengage** [comment]
Its working for me. https://ibb.co/hQixFa

**Comment by killengage** [comment]
https://admin.corehqservers.com

You only need to change your settings, key is to short.

**Comment by mpoonuru** [comment]
You want me to change the APP KEY to 32 ?

**Comment by mpoonuru** [comment]
The appkey generator not working.

**Comment by killengage** [comment]
http://api.gamerethos.net/random_key

**Comment by killengage** [comment]
working !

**Comment by mpoonuru** [comment]
I used Randomkeygen site for the key. Default username/password not working. You want me to create a new user and change the role value to 1 in DB?

**Comment by killengage** [comment]
Yes that should work to get you logged in.

**Comment by mpoonuru** [comment]
if this works, I buy you beer my friends! I am very desperate about this. When I am at office, I can't access procon or any other tools. This site would give me an overview of what's happening in my server.

**Comment by killengage** [comment]
For the live scoreboard to work you need to enter your RCON key that you received from the server hoster.

**Comment by killengage** [comment]
No go ahead, you can change the DB value for the new user.

**Comment by mpoonuru** [comment]
Guys! Let's celebrate! Working! Thanks a lot my friends! Share me the link for the beer! :)

**Comment by killengage** [comment]
Have fun !!

**Comment by mpoonuru** [comment]
Please share me the link for the donation!

**Comment by killengage** [comment]
info @skylenz.eu , but you don't have to !

**Comment by mpoonuru** [comment]
I am sorry! what is that bro?

**Comment by killengage** [comment]
Ow im sorry, its my paypal

**Comment by mpoonuru** [comment]
So, I can donate to info@skylez.eu right?

**Comment by killengage** [comment]
info@skylenz.eu yes its my company paypal. But again you don't have too :)

**Comment by killengage** [comment]
I see you added servers :)

**Comment by mpoonuru** [comment]
LOL, yea bro. This is the only way I can handle my servers,

**Comment by killengage** [comment]
Don't forget to add your RCON key so the live view is working too.

**Comment by mpoonuru** [comment]
Yeah My Friend! thank you, I just added the RCON password.  
Sent you a beer my Friend! I will contact you again if I need you guys help. You can add me on Linkedin.

**Comment by killengage** [comment]
Whats you linkedin ?

**Comment by mpoonuru** [comment]
https://www.linkedin.com/in/mallikharjuna-poonuru-17302032/

**Comment by mpoonuru** [comment]
let me know after you note it, I will delete the message for security reasons!

**Comment by killengage** [comment]
Ok delete

**Comment by killengage** [comment]
I delete my e-mail as well

**Comment by mpoonuru** [comment]
Super! Thank you my Friend! Please do send me an invite, Can you please ask  prophet also to send me an invite in linkedin?

**Comment by mpoonuru** [comment]
Can you please delete the Domain  name also my friend?

**Comment by Prophet731** [comment]
Glad you were able to get it running. Thanks @killengage for helping him. I fell asleep after writing that post up top. I had a long day. :(

**Comment by killengage** [comment]
No worries :) Glad i could help. 

Verstuurd vanaf mijn iPhone

**Comment by mpoonuru** [comment]
Hey Guys!

Live Scoreboard is the only issue at this moment. Could not connect to server. It may be offline or port is closed. Please try again later.

**Comment by Prophet731** [comment]
https://github.com/Prophet731/BFAdminCP/wiki/FAQ#5-error-connection-could-not-be-established-to-game-server

Read that as it explains what you need to do to fix it.

**Comment by mpoonuru** [comment]
Hey Prophet,
thanks, I did already raised a ticket to those guys. Linkedin? Here is my linkedin https://www.linkedin.com/in/mallikharjuna-poonuru-17302032/

Let me know bro, when you note it down, I will remove!

**Comment by mpoonuru** [comment]
Hi XXXXX,

Your servers have no firewall restrictions at this time where this should not be an issue. Please check this again.

Please let us know if you need further assistance.


This is the answer from the Hosting provider!

**Comment by mpoonuru** [comment]
This is fixed now! Thanks a lot Prophet! Don't forget to Add me on Linkedin. How can I test the new version?

**Comment by mpoonuru** [comment]
Hi, we can't ban an offline player using BFADMINCP?

**Comment by sitekeeper** [comment]
Search for a player name and once on their page at the top click on current ban and then just create ban.

Bob

**Comment by Prophet731** [comment]
What sitekeeper said. You're able to ban offline players.

**Comment by mpoonuru** [comment]
That's awesome friends. Let me try that.

**Comment by mpoonuru** [comment]
One more question, how to search for server up time, no of players map statistics?

**Comment by sitekeeper** [comment]
Well in Version 2.1.0 you can go to Live Scoreboard and see uptime, round info etc and go to SERVERS / listings and click on server you want for other stats. Other versions are a little different. We also use Stats page provided by Ty_ger07 for other stats, as it uses the same info as BFAdminCP.  Ours is here http://www.p4fun.org/players/ and BFAdminCP  is at http://www.bfplayforfun.org


Bob

**Comment by mpoonuru** [comment]
Wow, this looks nice, can please check what I am missing, https://admin.corehqnetwork.com and https://ap.corehqnetwork.com

**Comment by sitekeeper** [comment]
Nice but I could not get in  BFAdminCP first I got 500 error and never got confirmation email. Do you use a platoon stats page? http://www.p4fun.org/bf4-servers/p4fun-platoon and plain http://www.p4fun.org/platoon/   it is from http://www.ezstats.org/

Bob

**Comment by mpoonuru** [comment]
Yeah, I am trying to change the Mailgun to my domain but somehow I messed it. I don't know how to do it.

**Comment by mpoonuru** [comment]
Offline player ban is not available in 2.0.2? When we click on current ban there is nothing to click

**Comment by mpoonuru** [comment]
@sitekeeper how did you add the list in BFAdminCP? Can you please tell me?

**Comment by sitekeeper** [comment]
@mpoonuru  

Sorry what list?

Bob

**Comment by mpoonuru** [comment]
@sitekeeper 

screenshot attached dude. 
![listing](https://cloud.githubusercontent.com/assets/24477255/24655197/e07d1d78-195a-11e7-960d-e6c0b99b27c1.png)

**Comment by mpoonuru** [comment]
@sitekeeper 

dude, how did you manage to add today's visit and yesterday's visit?

Here is the screenshot.
![todaysvisit](https://cloud.githubusercontent.com/assets/24477255/24655251/241719d0-195b-11e7-9fb8-4e6e5661f768.png)

**Comment by mpoonuru** [comment]
@Prophet731 @sitekeeper 

I get the warnings like tooltip deprecated, use uitooltop instead. How to deal with it? You have any cdn reference for this Angular.js in our BFAdminCP code?

screenshot attached. 
![angularissue](https://cloud.githubusercontent.com/assets/24477255/24655325/6d61dcba-195b-11e7-9384-6f7a3e4db3ec.png)

**Comment by sitekeeper** [comment]
Oh ok, I think that is just part of the updates to Version 2.1.0. there were several features in it that I needed, so I have been using it since it came out.  My favorite is that lets you use RSS live feeds for Ban/reports like here.  http://www.p4fun.org/bans Some of the older versions had other useful features too but were lacking others.

Bob

**Comment by mpoonuru** [comment]
Where I Can download the V 2.1.0 dude? Whenever I try to download I get 2.0.3 version.

**Comment by sitekeeper** [comment]
I think it is still at https://github.com/Prophet731/BFAdminCP/tree/dev-laravel5  I  used the Dev-Laravel5 version but I would check with Prophet731 to make sure it is still active. I used composer to install it, I am on a good cpanel host.

Bob

**Comment by mpoonuru** [comment]
I tried to use composer but I get internal server error when i access the website. I am not sure what I did wrong there? Can you please give me the correct composer command to download the dev-larvel5 ?

**Comment by sitekeeper** [comment]
They are on bottom of the page, on that link

**Installing Dev Version**

I will assume you already have a webspace setup for this. If not just follow directions above to get the basics setup then come back here. All you should need to do is follow the commands and you should be up and running.

Make sure the directory is empty.

cd /path/to/bfacp
git clone https://github.com/Prophet731/BFAdminCP.git .
git checkout dev-laravel5
composer install --no-scripts
chmod -R 0777 storage
chmod -R 0777 public/js/builds
cp .env.example .env
After you ran those command edit the file .env with the necessary information then save the file. Next enter these commands.

php artisan migrate --force
php artisan db:seed --force
If you were running a previous version then you will need to run this command as well.

php artisan bfacp:reseed
You should be good to go now. Make sure that you update the subdomain to point to the public folder for its directory (not a redirect). If you wish to update to the latest version of this branch just do a git pull.

**Comment by sitekeeper** [comment]
Yeah @Prophet731 is your best hope he is great, and helped be a lot at first and I appreciated and donated to him a few times for his great work!

Bob

**Comment by mpoonuru** [comment]
@Prophet731,  can you please help to to use composer command using shell to download dev- larvel5?

**Comment by Prophet731** [comment]
@mpoonuru 

There are instructions posted above and in the readme on how to install it. 

https://github.com/Prophet731/BFAdminCP/tree/dev-laravel5#installing-dev-version

If you run type in the command `composer` in the shell you can see if composer is installed or not. If it's not [these instructions](https://getcomposer.org/download/) tell you how to get it. Follow the **Command-line installation**

**Comment by mpoonuru** [comment]
Hi Dude, 

Composer is installed. I don't have git, when I use the composer command as mentioned in the instructions I get the master code not the dev, can you please give me the composer command to to install dev

**Comment by Prophet731** [comment]
Oh, I never pushed the composer updates for that. One sec let me push them up and test it out. I'll reply if it's successful.

**Comment by Prophet731** [comment]
Ok, looks like everything's good now. Delete the contents of the directory and try it again. Also git is required on the system you're using to install it on. As composer relies on it.

**Comment by mpoonuru** [comment]
Sure, Tell me one thing bro,

If I download and run all the commands in my local PC then zip the contents and move that to my Webshoting will work? If this works, then I can use my local PC for cloning and working on the code then move it to webhosting. Will this work?

**Comment by Prophet731** [comment]
You can but make sure all files get uploaded, otherwise it will fail. It's just easier to do everything on the server usually.

**Comment by mpoonuru** [comment]
Internal Server Error

The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator, webmaster@cp.corehqnetwork.com and inform them of the time the error occurred, and anything you might have done that may have caused the error.

More information about this error may be available in the server error log.

Additionally, a 500 Internal Server Error error was encountered while trying to use an ErrorDocument to handle the request.

**Comment by Prophet731** [comment]
> Once uploaded you will need to modify some file and folder permissions. Change the files and folders permissions under storage recursively to 0777. This includes the storage folder itself. Also do this for the builds folder located at public/js/builds

Did you apply the required permissions on the server side? Also check the logs located under the `storage/logs` folder. If there is any logs attach the latest one here. Don't copy and paste, attach it as a file.

**Comment by mpoonuru** [comment]
Sorry too much work at office, tiered, couldn't respond to you quickly.
[Error.log.pdf](https://github.com/Prophet731/BFAdminCP/files/906221/Error.log.pdf)

**Comment by Prophet731** [comment]
Make sure you delete all the tables that start with `bfacp_` in the database. It's trying to re add those but it won't since it already has them. After you delete the tables just rerun the migration commands and see if that resolves the problem.

**Comment by mpoonuru** [comment]
Sure dude, I will try it out and let you know, hectic work today glued to the laptop screen.

**Comment by mpoonuru** [comment]
Still getting the same error my friend! Did everything still getting the 500 error. May be I am doing something wrong? If somebody can get me the complete zip file, I will try to download it and then try it.

**Comment by Prophet731** [comment]
Try this, it's the latest build that it generated. 

https://sourceforge.net/projects/bfacp/files/dev-laravel5-6ce2aa300b2a509d6192cb89d304789859b01df9.zip/download

**Comment by mpoonuru** [comment]
Hi bro,

I tried that but got the same error. Screenshot attched
![img_1551](https://cloud.githubusercontent.com/assets/24477255/24830446/9ef43282-1ca3-11e7-9fa2-79ff1d8ebdcb.PNG)

**Comment by Prophet731** [comment]
Alright delete the `bfacp_` tables in the database then run this [SQL script](https://raw.githubusercontent.com/Prophet731/BFAdminCP/dev-laravel5/scripts/setup.sql) on the DB. Don't run the migrate or seed commands after you do that. See if that fixes your problem.

**Comment by mpoonuru** [comment]
Hi dude,

I tried this but no luck. Even I did create a new subdomain to retest this but it failed. Still I am getting the Internal server Error.

**Comment by Prophet731** [comment]
Look for a file called `error_log` somewhere under the subdomain or on your control panels for your webhost (if you use one). If you can get that log and post it i'll be able to tell more why it's failing.

**Comment by mpoonuru** [comment]
Hey Dude, my wehosting provider helped me to resolve the issue, public/ index.php file permission issue it seems.

**Comment by mpoonuru** [comment]
When I login, I get this error:
 Fatal System Error!

This cache store does not support tagging.

**Comment by mpoonuru** [comment]
php artisan db:seed --force
Seeded: OptionsTableSeeder


  [BadMethodCallException]
  This cache store does not support tagging.

**Comment by mpoonuru** [comment]
Hey Bro,

Somehow theme is not getting loaded properly. Could you please help me? 
![failed _ corehq admin control center](https://cloud.githubusercontent.com/assets/24477255/24844346/90a7f572-1dc7-11e7-9423-0bba31b633e5.png)

**Comment by mpoonuru** [comment]
They are unable to find the issue. They are saying that it's an application issue. Can you please help me?

**Comment by Prophet731** [comment]
Did you edit any code in the application? Besides the .env file.

**Comment by mpoonuru** [comment]
No My Friend! I didn't even touch anything! If you want to verify, I can give you my credentials. The most unfortunate thing is, this theme is failing for all other subdomains where ever I create except https://admin.corehqnetwork.com  . Can you please help me? Where I can share my Hosting username/password details?

**Comment by Prophet731** [comment]
Before we do that I want you to try something first. Download the source from github [here](https://github.com/Prophet731/BFAdminCP/tree/dev-laravel5), then I want you to re-upload & overwrite the `public` directory and the `resources` directory.

Also, when you changed the cache driver to `array` that means nothing will get cached once the page has finished loading. This will cause lots of hits to your database on each request the application/user does. Just an FYI. If you can try and see if you can use `memcached` or `redis` if your hosting provider supports those.

**Comment by mpoonuru** [comment]
After the re upload, you want me to run the php artisan stuff?

**Comment by Prophet731** [comment]
No, don't run those.,

**Comment by mpoonuru** [comment]
you can send me an email to admin@corehqnetwork.com bro, so that I can share you the details via email.

**Comment by Prophet731** [comment]
Did you delete the files from your webhost? It's showing a 404 now.

**Comment by mpoonuru** [comment]
Yeah Bro! Completely Deleted! And doing a fresh one for testing! :(

**Comment by mpoonuru** [comment]
I just copied the new content. Can you please access https://ba.corehqnetwork.com now? I haven't accessed it yet.

**Comment by Prophet731** [comment]
Set the index.php permissions to 0755.

**Comment by mpoonuru** [comment]
Yeah bro! I set it now, but my hosting provider told me to use 0644 for the index.php file. That's how their webserver works it seems.

**Comment by Prophet731** [comment]
Oh, then set it to that then if it worked before.

**Comment by Prophet731** [comment]
Are you using cloudflare by any chance?

**Comment by mpoonuru** [comment]
Yeah! Dude!

**Comment by Prophet731** [comment]
Can you disable it for that domain? All the code checks out on the UI side.

**Comment by mpoonuru** [comment]
Domain or sub domain?

**Comment by Prophet731** [comment]
ba.corehqnetwork.com for that domain, disable it for that one.

**Comment by mpoonuru** [comment]
Hey bro,

disabled the cloudflare, cleared the cache, enabled the development mode.

**Comment by Prophet731** [comment]
Ok, let me test something on my side so give me a min.

**Comment by Prophet731** [comment]
Ok, your stylesheet doesn't match the one that's in the repo or my local copy. Did you update or modify any of those files? Because that file you have is too small in filesize and in lines. You can compare them each other. 

**Source:** https://raw.githubusercontent.com/Prophet731/BFAdminCP/dev-laravel5/public/css/style.css

**Yours:** http://ba.corehqnetwork.com/css/style.css?v=1

Try re-uploading that file from the repo instead.

**Comment by mpoonuru** [comment]
I did replace the file bro.

**Comment by Prophet731** [comment]
It shouldn't. I don't have a minify for those CSS. It just links them directly. Only one it minifies is the JS and those aren't causing that. Are you sure it's uploading the files fully? Cause until that file matches the one on github you're going to have the display issue.

**Comment by mpoonuru** [comment]
Could you please send me an email dude! I will share my details, you can verify, please? I am copying the files and extracting them.

**Comment by Prophet731** [comment]
You don't need to share the details with me. Now that I know the problem, which is an easy one to fix to be honest, from what I originally thought. You said you had shell access right? Ok so do these commands instead of using the cpanel file explorer. That could be the problem too.

In the shell terminal, `cd` to the `public` directory and go into the `css` folder. For example,
`cd /path/to/bfacp/public/css`. Once you do that run the following command. This will have the server download the file and overwrite it.

`wget -O style.css https://raw.githubusercontent.com/Prophet731/BFAdminCP/dev-laravel5/public/css/style.css`

If that fails to fix the mismatch style issue then we'll try uploading it through another program like filezilla.

**Comment by mpoonuru** [comment]
Bro, I did try this, still the same issue. But I used a browser extension called use css for chrome and added this file and theme loads perfectly. But the real website fails to load the theme.

**Comment by mpoonuru** [comment]
Can you try to register an account bro? It is failing to create an account!

**Comment by Prophet731** [comment]
I can't, getting a 500 error now. You tried that wget command for the file already? If it's still doing it then try the filezilla method. If that STILL fails contact your provider and ask them why that file isn't being uploaded correctly.

**Comment by mpoonuru** [comment]
Sure bro, I will check with them. :( But why it is failing to register an account? Unable to handle any requests!

**Comment by mpoonuru** [comment]
Thanks a lot for your great help! Have a great time my friend!
