### ISSUE TITLE
Can't delete Users

### ISSUE THREAD

**Issue by antitoxis** [AdKats/BFAdminCP#254]
Hey,
i want to try to delete an user, but it do anything.

**Comment by mpoonuru** [comment]
can you please let me know where exactly you are trying to delete a user? Site User or Adkats user?

**Comment by antitoxis** [comment]
https://puu.sh/vtrcX/ae6c5b4a5f.png
I try to delete adkats users from the site.
But after the confirm nothing happens

**Comment by mpoonuru** [comment]
Can you verify that in your Procon layer Adkats whether the user has been deleted or not?

**Comment by antitoxis** [comment]
The user isn't delete. I can only delete this users with procon.

**Comment by Prophet731** [comment]
Sorry for the late reply, work has been keeping me busy and tired.

Go to the page where you want to delete the user, then open the developer tools (F12) in chrome and go to the console tab, make sure to check the box "Preserve Log". Once you have done that then try and delete the user. If you get an error (red text), copy and paste it here or take a screenshot of it.
