### ISSUE TITLE
Fed up

### ISSUE THREAD

**Issue by SpankDaddy** [AdKats/BFAdminCP#259]
Hi Prophet, 

I've been over this a million times trying to get this to work and I'm about fed up. I had issues before and you helped with those, but the CP never connects to our server for the live scoreboard. Now I'm back to square one, with no popout menus - so I can't get into the Adkats/Site Management and the live scoreboard still isn't connecting to the server... seriously. 

"Fatal Error! The request couldn't complete due to a server side error. Please choose another server or retry. Notify an administrator if this error persists. "

I have uninstalled, removed databases, read the instructions, reinstalled, done everything possible and it just doesn't want to work correctly. 

http://bgcadmincp.bgcgaming.com 

One last attempt and I'll be done with this, if you can assist.

**Comment by mpoonuru** [comment]
Make sure that your game server port is enabled on your hosting provider web server else ask them to open the game server port.

**Comment by Prophet731** [comment]
Well I can see your first problem now. When I go to the URL it redirects me to this url `http://bgcadmincp.bgcgaming.com/public/` it shouldn't do that. That's why the files aren't working. The instructions say it needs to be the document root path to the public folder. Not the redirect.

What is your web server control panel? (cpanel, etc..)
When are you available? I have today off from work so I can help out.

**Comment by SpankDaddy** [comment]
Thanks Prophet - I'm on TS and can give you the information. Can you join me?

TS info:  battlefieldgamers.bgcgaming.com 

Cheers!

**Comment by SpankDaddy** [comment]
I appreciate the help today Prophet! Million thanks! Just have to see if they will open the game ports now. 

Cheers!

**Comment by SpankDaddy** [comment]
Prophet - So they opened the ports and it's connecting to the server fine now. I am however seeing this error when attempting to send a test chat to the server - 

ErrorException in CurrentRoute.php line 29:
The current route (POST /servers/admin/scoreboard/say/{one?}/{two?}/{three?}/{four?}/{five?}) is not named - please check routes.php for an "as" parameter (View: /home1/xxx/public_html/xxx/resources/views/layout/main.blade.php)

Any ideas?

**Comment by Prophet731** [comment]
Nope, never seen that error and don't know why it's happening. It's not even programmed that way for it. In the `storage/logs` folder you should have a log file for today's date. Download that and upload here. Attach the file to your comment.

**Comment by mpoonuru** [comment]
Looks like you are using the main domain instead of subdomain. Can you please use subdomain for the BFAdminCP?

**Comment by SpankDaddy** [comment]
Uploaded. 

[laravel-2017-06-14.txt](https://github.com/Prophet731/BFAdminCP/files/1074810/laravel-2017-06-14.txt)

**Comment by Prophet731** [comment]
Ok I got it, I removed the link for security reasons.

**Comment by Prophet731** [comment]
I joined your TS as I need to get on teamviewer with you. It's actually a problem with one of the packages but I don't know why. It's never caused that before.
