### ISSUE TITLE
Metabans feed does not work, what am I doing wrong?

### ISSUE THREAD

**Issue by xX-TONNE-Xx** [AdKats/BFAdminCP#260]
Have at:
Metabans API: API key, I've entered
Metabans Username: my name registered with Metabans
Metabans Account: ??? What value does it come in? Is not that the same as the username?

Metabans is enabled, but Metabans feed does not work.

![unbenannt](https://user-images.githubusercontent.com/29067573/27238315-ae7385aa-52cc-11e7-9e34-e052dcfa02e3.JPG)
![unbenannt2](https://user-images.githubusercontent.com/29067573/27238502-77efd88e-52cd-11e7-88a8-ef521cf43698.JPG)

Illustrations are only examples

**Comment by Prophet731** [comment]
Remove the `metabans.com/` and it will work. As long as you have bans posted to that account you want to pull.

**Comment by xX-TONNE-Xx** [comment]
nothing changes. Does the server run as ranked, or does this also with official server?

**Comment by xX-TONNE-Xx** [comment]
Hi,
in recent days, some have been banned by metabans, but these do not appear in the feed. There is still "Error loading metabans feed"

**Comment by Prophet731** [comment]
If you have no bans under that account it won't show up. Also make sure your api key is valid and not expired.

**Comment by xX-TONNE-Xx** [comment]
i have 34 Bans at metabans.com/inoT bzw. @inoT
