### ISSUE TITLE
install issue centos7/php7

### ISSUE THREAD

**Issue by vanucci** [AdKats/BFAdminCP#261]
Hello 

I used to use this a couple years back, and now ive got a server again im back to using it. 

I have followed the instructions, added the keys, changed folder file permissions

when i go to the subdomain this is installed at, i get this 

https://i.gyazo.com/59b38c85a04e620e89d3969078dd8db2.png

Im using same DB details as adkats also, I must have missed something.  I know that my system specs most liekly isnt the issue ( i hope) ive just added them incase.

**Comment by Prophet731** [comment]
Sorry for the late reply, I never got the notification for this. Currently the bfacp doesn't support PHP7 natively. I haven't kept it updated for that as i've been busy and haven't had time to work on it. As for it not loading, you missed having the `document root` point to the public folder that's provided. This is not the same as a redirection. You will need to use the last stable version of PHP 5.6 for it to run correctly.

**Comment by vanucci** [comment]
thanks for getting back to me. Will php7 be supported in the future if time allows ?

**Comment by Prophet731** [comment]
Possible yeah, I had plans to do that but I've just been way too busy to work on it.
