### ISSUE TITLE
Style Issues

### ISSUE THREAD

**Issue by alex809** [AdKats/BFAdminCP#263]
The bootstrap style isn't working correctly.
I could fix this myself but too lazy to modify the templates lol

https://image.prntscr.com/image/oxSkaGWUTqauRky-Ajs1yQ.png

Just needs the HTML fixed so that the actions stack beside the chat, Still annoying with all that empty space.

**Comment by Prophet731** [comment]
Actually its working fine. On the right side is two blocks that will pop up when an admin and/or spectator is in the server. They are hidden until they at least find 1 player in those slots.
