### ISSUE TITLE
Fatal Error on Systemlogs and Updater

### ISSUE THREAD

**Issue by xX-TONNE-Xx** [AdKats/BFAdminCP#265]
Fatal Error 500 for Updater and Systemlogs. 
Error in systemlogs is: 
`Use of undefined constant GLOB_BRACE - assumed 'GLOB_BRACE' `

and for Updater: 
`Client errorResponse [url] https://api.github.com/repos/Prophet731/BFAdminCP/releases/latest [status code ] 403 [reasonproposal] Forbidden`

Should this be so?

**Comment by xX-TONNE-Xx** [comment]
Hi,
and now a new Fatal Error on the Updater:

`Cannot use vierbergenlars\LibJs\String as String because 'String' is a special class name`

**Comment by Prophet731** [comment]
Which version are you running? And what php version do you have?

**Comment by xX-TONNE-Xx** [comment]
BFAdminCP Version 2.0.2
OS: SunOS l
PHP: 7.0.22

**Comment by Prophet731** [comment]
That version doesn't support php 7 that's why you are getting the error. The BFACP doesn't support php 7 yet.

**Comment by xX-TONNE-Xx** [comment]
until yesterday everything went wonderfully, down to the update & systemlogs. But today nothing works. The error when accessing the page is "Error in exception handler". But I have not changed anything.

**Comment by xX-TONNE-Xx** [comment]
Problem with the error message "Error in exception handler" has been fixed. It was the IPv6 protocol. Somehow he has problems with it.

**Comment by Prophet731** [comment]
Oh yeah, I remember a bug about that a while ago with IPv6.
