### ISSUE TITLE
Request? Add auto-translation on non-english chatlog

### ISSUE THREAD

**Issue by iraqiboy90** [AdKats/BFAdminCP#58]
Hello

I dont know if you get the time for this, and idk if this has been mentioned before, but if you can, can you implement an auto translation feature that translate non-english chats on the panel, including the live chat box on the leaderboard, with a quick switch to turn on/off?

**Comment by ColColonCleaner** [comment]
You would need an API key for some translation service. Finding a service with a decent response time and API would be the first step.

**Comment by Prophet731** [comment]
Also, from what i've seen so far, most of these are paid services and charge by X characters/words you can use per month.

For google, see https://cloud.google.com/translate/v2/pricing

So I could add it but it would be up to the user to setup the billing for that. Not to mention if you want to translate all that it will add up very quickly.

**Comment by tmiland** [comment]
How about a button or something on the side of the string?

So you dont have to translate everything, but just the stings you choose? :)

**Comment by iraqiboy90** [comment]
@Prophet731 yes, i've seen the pricing :)
since the API response time is slow then it cant be applied to the live chatbox
and with tmiland's idea it wont add up to 1million character quickly :)

**Comment by ColColonCleaner** [comment]
You won't have a response time issue with google. 

What does the language enforcer use? I haven't looked at it. Does it actually determine which language is being spoken or does it just trigger on certain words/phrases? 

It would be nice to have an automatic enforcer of English only in chat, and automatically have the translated message stored in the database like "original message (translated message)". In that case it would be be up to an extension for AdKats to use that.

**Comment by iraqiboy90** [comment]
I had the discussion of forcing english only with my community members, but it was turned down with the following arguments:
- If we accept players from non-english countries, then we should accept the language they use.
- If the server is being hosted in non-english country, then it would be too much to force people to speak/write english
- Unfair for those who doesnt know the language.

P.s. The Language enforcer plugin: ""Basically the plugin aims to prevent swearing orgies.""
https://forum.myrcon.com/showthread.php?7699-Language-Enforcer-1-0-2-0-%28Jan-4-%29&highlight=Basically

**Comment by NexonSU** [comment]
As i know, Frostbite RCON using ISO 8859-1, so this is imposible.
Only way to complete this feature, is using PBUCON instead RCON.
Or visit DICE office and tell them what using Latin 1 in 2016 is cancer.
