### ISSUE TITLE
REQUEST : Add comment functionality to player profiles

### ISSUE THREAD

**Issue by ChaT0n** [AdKats/BFAdminCP#90]
On the banned profile of a player, to be able to add near the reason a comment that will show when we pass the mouse over the note icone.
So the banllist will be like:
Nickname, GUID or EA_ID (iwth links to battlelog or istats or metabans), reason, date of the ban, expiration date, server where he was banned,  banned by (only admins can see it), comments.

**Comment by Prophet731** [comment]
I'll see what I can do. There was the disqus comment system in the previous version but I don't think a lot of people used it.

**Comment by Prophet731** [comment]
Going to add this in version 3. Which will be the compatable version for AdKats 7
